name: workflow

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'


jobs: 
  integration:
    name: Continous integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: action/checkout@v3

      - name: Lint Code
        run: echo "Linting repository"

      - name: Run unit test
        run: echo "Runing unit tests"
